### ISSUE TITLE
Can't install publicsuffic=x per instruction

### ISSUE THREAD

**Issue by jb510** [google/namebench#7]
When I get public suffix:

```
  % go get code.google.com/p/go.net/publicsuffix                                                                                                 warning: code.google.com is shutting down; import path code.google.com/p/go.net/publicsuffix will stop working
```

build seems to succeed, but then on run

```
± % ./namebench                                                                                                                                  2015/12/22 18:36:53 URL: http://127.0.0.1:65086/
2015/12/22 18:36:53 error running /Applications/node-webkit.app/Contents/MacOS/node-webkit ./ui/app.nw: fork/exec /Applications/node-webkit.app/Contents/MacOS/node-webkit: no such file or directory
```

**Comment by KevOrr** [comment]
When you visit that url it redirects to github.com/golang/go. I'm able to grab publicsuffix by pulling from golang.org:

    $ go get golang.org/x/net/publicsuffix

And changing the import line in `history/filter.go` to reflect this change:

    @@ -4,3 +4,3 @@
     import (
    -	"code.google.com/p/go.net/publicsuffix"
    +	"golang.org/x/net/publicsuffix"
     	"log"

Though I still have the same problem as you where it seems to be looking for for an OSX-style path

**Comment by GinoM** [comment]
Thank you, I had the same problem, will someone please fix filter.go?

**Comment by Chaz6** [comment]
The instructions in README.md still says ```go get code.google.com/p/go.net/publicsuffix``` which fails for me so:-

```
package code.google.com/p/go.net/publicsuffix: unrecognized import path "code.google.com/p/go.net/publicsuffix" (parse https://code.google.com/p/go.net/publicsuffix?go-get=1: no go-import meta tags (meta tag github.com/golang/go did not match import path code.google.com/p/go.net/publicsuffix))
```

**Comment by jeffbyrnes** [comment]
@Chaz6 did you read [this comment above](https://github.com/google/namebench/issues/7#issuecomment-268032402)? That change will let you build the project.

You can also just grab the code from my PR; that’ll sort you out, too.

**Comment by Chaz6** [comment]
Yes, just pointing out that the README also needs updating.

**Comment by jeffbyrnes** [comment]
@Chaz6 yep, I’ve had it corrected in my PR for a while: https://github.com/google/namebench/pull/9/files#diff-04c6e90faac2675aa89e2176d2eec7d8R31

Maybe one day @tstromberg will get a chance to merge it in 🤞

**Comment by jeffbyrnes** [comment]
🎉 celebrate, one & all!
